server:
  port: 6666
  
spring:
  datasource:
   url: jdbc:mysql://localhost:3306/mydb
   username: root
   password: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
       format_sql: true  

  application:
    name: product-service
 
eureka:
  client: 
    register-with-eureka: false
    fetch-registry: true

 

      


      
      
    
      
      
    