#spring.datasource.url=jdbc:mysql://localhost:3306/javabatch
#spring.datasource.username=root

#spring.datasource.password=root

#spring.jpa.hibernate.ddl-auto=create
server:
  port: 8888
  
spring:
  datasource:
   url: jdbc:mysql://localhost:3306/javabatch1
   username: root
   password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
       format_sql: true  
      